services:
  web:
    image: nginx
    container_name: web
    restart: always
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT}:80"
    networks:
      - internal
  workspace:
    build: .
    restart: always
    container_name: workspace
    volumes:
      - .:/var/www/html
    networks:
      - internal
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal
    container_name: db
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOSTS=db
      - PMA_PORT=${DB_PORT}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_ARBITRARY=1
    networks:
      - internal
    container_name: phpmyadmin
networks:
  internal:
volumes:
  mysql-data:
